### ISSUE TITLE
material

### ISSUE THREAD

**Issue by dadauncle** [Team-1111/bankbankatm#1]
[Bank System.pdf](https://github.com/Team-1111/bankbankatm/files/1491374/Bank.System.pdf)
[Bank System.docx](https://github.com/Team-1111/bankbankatm/files/1491370/Bank.System.docx)

**Comment by irufaan** [comment]
Why bank system? we only need to do ATM

**Comment by irufaan** [comment]
Please dont upload project related useful files here,, He we Open and Close the issues we have in our project,
