### ISSUE TITLE
Diagrams for Final Project Report

### ISSUE THREAD

**Issue by irufaan** [Team-1111/bankbankatm#10]
I have checked that which diagrams we need to finish for Final report. So far, we have done few diagrams. But we need to finish all the diagrams if we want get more marks from the project.

![image](https://user-images.githubusercontent.com/18720307/33854446-c16eb262-defc-11e7-9529-6f15afd4fe81.png)

![image](https://user-images.githubusercontent.com/18720307/33854404-9ba771ae-defc-11e7-9d96-0f701a480133.png)

1. Activity Diagram - Need to be done
2. Collaboration Diagram - Need to be done
3. Sequence Diagram - Done - but need to modify
4. Component Diagram - Need to be done
5. Deployment Diagram - In progress but - Need to be done
6. State Chart Diagram - Need to be done
7. Class Diagram - Done - but need to modify
8. Use-Case Diagram - Done - but need to modify

**Comment by irufaan** [comment]
@dadauncle which diagrams you will do?

**Comment by dadauncle** [comment]
I finish these three at  first：
![47448dffd0ca135fe302705eaa7097c2](https://user-images.githubusercontent.com/33367636/33871812-149745e2-df4f-11e7-931d-b78f7b085c1b.png)
![439ba406699989cc09fe17bcab7fb450](https://user-images.githubusercontent.com/33367636/33871818-1a88e1c2-df4f-11e7-9ea8-265d9b4b4683.png)

**Comment by irufaan** [comment]
@dadauncle  Did you finish three diagram that you suppose to do,  @yoSir  He has done great work for other remaining diagrams.  Now only we need your three diagram plus state chart diagram.
