### ISSUE TITLE
Why not we use best features available in GitHub?

### ISSUE THREAD

**Issue by irufaan** [Team-1111/bankbankatm#2]
Right now our Repository doesn't have any projects yet because we are doing everything in <>Code.
Why not we Create Project ? 
Why not Assign the different Task to different team members?
Why not we communicate each other using GitHub rather than wechat or QQ?

Let me assign the first task to our Group Leader

**Comment by irufaan** [comment]
Please say something

**Comment by ZiwaYo** [comment]
I have created the project now.

**Comment by ZiwaYo** [comment]
I have assigned the task.

**Comment by irufaan** [comment]
Thank you , great Job
