### ISSUE TITLE
Defining the boundaries of the problem

### ISSUE THREAD

**Issue by irufaan** [Team-1111/bankbankatm#7]
Please find the problems we might have in ATM system, or What or Who might make problems for ATM. 
After this we will define the boundaries for those problems.

I would you guys to research little bit about boundaries of the problems might have in ATM system for this task.

**Comment by irufaan** [comment]
Please click the milestone tab and see more details of the task. you will see this on the top of all the issues and left side of New Issue button

**Comment by dadauncle** [comment]
Okay, I got it, thanks👌

**Comment by dadauncle** [comment]
okay，I got it👌

**Comment by dadauncle** [comment]
How about ATM crash not enough to customer withdraw money？🤔

**Comment by irufaan** [comment]
@dadauncle  yeah, that can be a problem, so what solution we need to make for this problem/?

**Comment by yoSir** [comment]
I have defined the boundaries for this system, and it's in the readme.md
